/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class DamageType 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 3678479991595962128L;
    private int id;
    private String title;
    private String sortPriority;
    private String createOn;
    private String updateOn;
    private String createdBy;
    private String updatedBy;
    private String createOnPersianDate;
    private String updateOnPersianDate;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public int getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (int value) { 
        this.id = value;
        notifyObservers(this.id);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("title")
    public String getTitle ( ) { 
        return this.title;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("title")
    public void setTitle (String value) { 
        this.title = value;
        notifyObservers(this.title);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sortPriority")
    public String getSortPriority ( ) { 
        return this.sortPriority;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sortPriority")
    public void setSortPriority (String value) { 
        this.sortPriority = value;
        notifyObservers(this.sortPriority);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("createOn")
    public String getCreateOn ( ) { 
        return this.createOn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("createOn")
    public void setCreateOn (String value) { 
        this.createOn = value;
        notifyObservers(this.createOn);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("updateOn")
    public String getUpdateOn ( ) { 
        return this.updateOn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("updateOn")
    public void setUpdateOn (String value) { 
        this.updateOn = value;
        notifyObservers(this.updateOn);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("createdBy")
    public String getCreatedBy ( ) { 
        return this.createdBy;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("createdBy")
    public void setCreatedBy (String value) { 
        this.createdBy = value;
        notifyObservers(this.createdBy);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("updatedBy")
    public String getUpdatedBy ( ) { 
        return this.updatedBy;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("updatedBy")
    public void setUpdatedBy (String value) { 
        this.updatedBy = value;
        notifyObservers(this.updatedBy);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("createOnPersianDate")
    public String getCreateOnPersianDate ( ) { 
        return this.createOnPersianDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("createOnPersianDate")
    public void setCreateOnPersianDate (String value) { 
        this.createOnPersianDate = value;
        notifyObservers(this.createOnPersianDate);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("updateOnPersianDate")
    public String getUpdateOnPersianDate ( ) { 
        return this.updateOnPersianDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("updateOnPersianDate")
    public void setUpdateOnPersianDate (String value) { 
        this.updateOnPersianDate = value;
        notifyObservers(this.updateOnPersianDate);
    }
 
}
