/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class InsurancePolicyTracking 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = -3205006066455901318L;
    private int id;
    private String aliasName;
    private String status;
    private String createOnPersianDate;
    private String centerName;
    private int insurancePolicyType;
    private String insuranceType;
    private int price;
    private String paymented;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public int getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (int value) { 
        this.id = value;
        notifyObservers(this.id);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("aliasName")
    public String getAliasName ( ) { 
        return this.aliasName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("aliasName")
    public void setAliasName (String value) { 
        this.aliasName = value;
        notifyObservers(this.aliasName);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
        notifyObservers(this.status);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("createOnPersianDate")
    public String getCreateOnPersianDate ( ) { 
        return this.createOnPersianDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("createOnPersianDate")
    public void setCreateOnPersianDate (String value) { 
        this.createOnPersianDate = value;
        notifyObservers(this.createOnPersianDate);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("centerName")
    public String getCenterName ( ) { 
        return this.centerName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("centerName")
    public void setCenterName (String value) { 
        this.centerName = value;
        notifyObservers(this.centerName);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insurancePolicyType")
    public int getInsurancePolicyType ( ) { 
        return this.insurancePolicyType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insurancePolicyType")
    public void setInsurancePolicyType (int value) { 
        this.insurancePolicyType = value;
        notifyObservers(this.insurancePolicyType);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceType")
    public String getInsuranceType ( ) { 
        return this.insuranceType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceType")
    public void setInsuranceType (String value) { 
        this.insuranceType = value;
        notifyObservers(this.insuranceType);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("price")
    public int getPrice ( ) { 
        return this.price;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("price")
    public void setPrice (int value) { 
        this.price = value;
        notifyObservers(this.price);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paymented")
    public String getPaymented ( ) { 
        return this.paymented;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paymented")
    public void setPaymented (String value) { 
        this.paymented = value;
        notifyObservers(this.paymented);
    }
 
}
