/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class TrackingCode 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 6666028628511306146L;
    private int id;
    private int insuranceTypeId;
    private int insuranceCentreId;
    private String insuranceCentreName;
    private int insuranceCompanyId;
    private String insuranceCompanyTitle;
    private String insurancePolicyNumber;
    private int personalityType;
    private String damageType;
    private String name;
    private String nationalCode;
    private String mobile;
    private String insuredProfile;
    private String refrencedUser;
    private String referenceCount;
    private String trackingCode;
    private String paymentType;
    private String paymentDate;
    private String paymentPersianDate;
    private String subDomain;
    private String insuranceTypeTitle;
    private String createOn;
    private String updateOn;
    private String createOnPersianDate;
    private String updateOnPersianDate;
    private List<TrackingDamageStatusTrackingCode> trackingDamageStatus;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public int getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (int value) { 
        this.id = value;
        notifyObservers(this.id);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceTypeId")
    public int getInsuranceTypeId ( ) { 
        return this.insuranceTypeId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceTypeId")
    public void setInsuranceTypeId (int value) { 
        this.insuranceTypeId = value;
        notifyObservers(this.insuranceTypeId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCentreId")
    public int getInsuranceCentreId ( ) { 
        return this.insuranceCentreId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCentreId")
    public void setInsuranceCentreId (int value) { 
        this.insuranceCentreId = value;
        notifyObservers(this.insuranceCentreId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCentreName")
    public String getInsuranceCentreName ( ) { 
        return this.insuranceCentreName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCentreName")
    public void setInsuranceCentreName (String value) { 
        this.insuranceCentreName = value;
        notifyObservers(this.insuranceCentreName);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCompanyId")
    public int getInsuranceCompanyId ( ) { 
        return this.insuranceCompanyId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCompanyId")
    public void setInsuranceCompanyId (int value) { 
        this.insuranceCompanyId = value;
        notifyObservers(this.insuranceCompanyId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCompanyTitle")
    public String getInsuranceCompanyTitle ( ) { 
        return this.insuranceCompanyTitle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCompanyTitle")
    public void setInsuranceCompanyTitle (String value) { 
        this.insuranceCompanyTitle = value;
        notifyObservers(this.insuranceCompanyTitle);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insurancePolicyNumber")
    public String getInsurancePolicyNumber ( ) { 
        return this.insurancePolicyNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insurancePolicyNumber")
    public void setInsurancePolicyNumber (String value) { 
        this.insurancePolicyNumber = value;
        notifyObservers(this.insurancePolicyNumber);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("personalityType")
    public int getPersonalityType ( ) { 
        return this.personalityType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("personalityType")
    public void setPersonalityType (int value) { 
        this.personalityType = value;
        notifyObservers(this.personalityType);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("damageType")
    public String getDamageType ( ) { 
        return this.damageType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("damageType")
    public void setDamageType (String value) { 
        this.damageType = value;
        notifyObservers(this.damageType);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
        notifyObservers(this.name);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("nationalCode")
    public String getNationalCode ( ) { 
        return this.nationalCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("nationalCode")
    public void setNationalCode (String value) { 
        this.nationalCode = value;
        notifyObservers(this.nationalCode);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("mobile")
    public String getMobile ( ) { 
        return this.mobile;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("mobile")
    public void setMobile (String value) { 
        this.mobile = value;
        notifyObservers(this.mobile);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuredProfile")
    public String getInsuredProfile ( ) { 
        return this.insuredProfile;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuredProfile")
    public void setInsuredProfile (String value) { 
        this.insuredProfile = value;
        notifyObservers(this.insuredProfile);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("refrencedUser")
    public String getRefrencedUser ( ) { 
        return this.refrencedUser;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("refrencedUser")
    public void setRefrencedUser (String value) { 
        this.refrencedUser = value;
        notifyObservers(this.refrencedUser);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("referenceCount")
    public String getReferenceCount ( ) { 
        return this.referenceCount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("referenceCount")
    public void setReferenceCount (String value) { 
        this.referenceCount = value;
        notifyObservers(this.referenceCount);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("trackingCode")
    public String getTrackingCode ( ) { 
        return this.trackingCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("trackingCode")
    public void setTrackingCode (String value) { 
        this.trackingCode = value;
        notifyObservers(this.trackingCode);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paymentType")
    public String getPaymentType ( ) { 
        return this.paymentType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paymentType")
    public void setPaymentType (String value) { 
        this.paymentType = value;
        notifyObservers(this.paymentType);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paymentDate")
    public String getPaymentDate ( ) { 
        return this.paymentDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paymentDate")
    public void setPaymentDate (String value) { 
        this.paymentDate = value;
        notifyObservers(this.paymentDate);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("paymentPersianDate")
    public String getPaymentPersianDate ( ) { 
        return this.paymentPersianDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("paymentPersianDate")
    public void setPaymentPersianDate (String value) { 
        this.paymentPersianDate = value;
        notifyObservers(this.paymentPersianDate);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("subDomain")
    public String getSubDomain ( ) { 
        return this.subDomain;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("subDomain")
    public void setSubDomain (String value) { 
        this.subDomain = value;
        notifyObservers(this.subDomain);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceTypeTitle")
    public String getInsuranceTypeTitle ( ) { 
        return this.insuranceTypeTitle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceTypeTitle")
    public void setInsuranceTypeTitle (String value) { 
        this.insuranceTypeTitle = value;
        notifyObservers(this.insuranceTypeTitle);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("createOn")
    public String getCreateOn ( ) { 
        return this.createOn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("createOn")
    public void setCreateOn (String value) { 
        this.createOn = value;
        notifyObservers(this.createOn);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("updateOn")
    public String getUpdateOn ( ) { 
        return this.updateOn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("updateOn")
    public void setUpdateOn (String value) { 
        this.updateOn = value;
        notifyObservers(this.updateOn);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("createOnPersianDate")
    public String getCreateOnPersianDate ( ) { 
        return this.createOnPersianDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("createOnPersianDate")
    public void setCreateOnPersianDate (String value) { 
        this.createOnPersianDate = value;
        notifyObservers(this.createOnPersianDate);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("updateOnPersianDate")
    public String getUpdateOnPersianDate ( ) { 
        return this.updateOnPersianDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("updateOnPersianDate")
    public void setUpdateOnPersianDate (String value) { 
        this.updateOnPersianDate = value;
        notifyObservers(this.updateOnPersianDate);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("trackingDamageStatus")
    public List<TrackingDamageStatusTrackingCode> getTrackingDamageStatus ( ) { 
        return this.trackingDamageStatus;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("trackingDamageStatus")
    public void setTrackingDamageStatus (List<TrackingDamageStatusTrackingCode> value) { 
        this.trackingDamageStatus = value;
        notifyObservers(this.trackingDamageStatus);
    }
 
}
