/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class TrackingDamageFileTrackinCode 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = -2137280064119068500L;
    private int id;
    private int trackingDamageStatusId;
    private String fileName;
    private String title;
    private String url;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public int getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (int value) { 
        this.id = value;
        notifyObservers(this.id);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("trackingDamageStatusId")
    public int getTrackingDamageStatusId ( ) { 
        return this.trackingDamageStatusId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("trackingDamageStatusId")
    public void setTrackingDamageStatusId (int value) { 
        this.trackingDamageStatusId = value;
        notifyObservers(this.trackingDamageStatusId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fileName")
    public String getFileName ( ) { 
        return this.fileName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fileName")
    public void setFileName (String value) { 
        this.fileName = value;
        notifyObservers(this.fileName);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("title")
    public String getTitle ( ) { 
        return this.title;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("title")
    public void setTitle (String value) { 
        this.title = value;
        notifyObservers(this.title);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("url")
    public String getUrl ( ) { 
        return this.url;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("url")
    public void setUrl (String value) { 
        this.url = value;
        notifyObservers(this.url);
    }
 
}
